name: Build

on:
  # workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*"
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      RUST_MIN_STACK: 16777216
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: supplypike/setup-bin@v4
        with:
          uri: "https://github.com/WebAssembly/binaryen/releases/download/version_122/binaryen-version_122-aarch64-linux.tar.gz"
          name: "wasm-opt"
          version: "122"
          subPath: "binaryen-version_122/bin"

      # - name: Test downloading Giant Swarm binary
      #   uses: giantswarm/install-binary-action@v3
      #   with:
      #     binary: "wasm-opt"
      #     version: "119"
      #     download_url: "https://github.com/WebAssembly/binaryen/releases/download/version_${version}/binaryen-version_${version}-x86_64-linux.tar.gz"
      #     tarball_binary_path: "*/binaryen-version_119/bin/${binary}"
      #     smoke_test: "${binary} --version"

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen@0.2.100

      - name: Show version information (Rust, cargo)
        run: |
          rustup update
          rustup -V
          rustup toolchain list
          rustup target add wasm32-unknown-unknown
          cargo -V
          rustc -V

      - name: Build
        run: |-
          cargo build --bins --release --verbose --target wasm32-unknown-unknown
          wasm-bindgen ./target/wasm32-unknown-unknown/release/connections-rs.wasm --out-dir ./pkg --typescript --target web
          wasm-opt ./pkg/connections-rs_bg.wasm -o ./pkg/connections-rs_bg.wasm -Oz --enable-simd

      - uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: pkg/
          compression-level: 9
